### ISSUE TITLE
Enable `log_errors` in php.ini by default

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/vip-quickstart#261]
Useful for debugging purposes.

**Comment by paulschreiber** [comment]
+1 this

I discovered that I had to `sudo touch /var/log/php-fpm-www-error.log` and `sudo chown www-data /var/log/php-fpm-www-error.log` to get logging to work and was about to file a bug.

**Comment by joshbetz** [comment]
#448 should have fixed this

**Comment by joshbetz** [comment]
https://github.com/Automattic/vip-quickstart/commit/1bdb375a8eab741d1f82b5e5b610d2c13f9668d5
