### ISSUE TITLE
Quickstart is slow

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/vip-quickstart#372]
Quickstart is slow. Pages often take 4-5s to load.

My configuration:
* MacBook Pro: 2.3 GHz Core i7, 16 GB of RAM, SSD
* VM "upgraded" to more RAM and CPUs
```
      config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
      end
```

When I run top during a WordPress page load, I often see 4 `php-fpm` processes, each one taking 25-30% CPU.

**Comment by joshbetz** [comment]
We need to turn off virtualbox shares. I had the main share switched to rsync and just the VIP folder shared with virtualbox native shares for a while and page loads were in the .2s range. There are a couple more things we need to work out before we can ship it though. An example is what to do with `local-config.php`. Rsync is only one way, so the local-config has to be updated every time the VM restarts. I'm not sure of a great way to fix it.

**Comment by paulschreiber** [comment]
Is there anything we can do to help with this? Is this on a branch we can test? CC @scottlee

**Comment by joshbetz** [comment]
https://github.com/Automattic/vip-quickstart/tree/feature-rsync

**Comment by brshewmaker** [comment]
Try NFS, if you are on a Mac or Linux and can get it to work for you, it works much faster than plain virtualbox shares.  

I changed this line: 
`config.vm.synced_folder ".", "/srv", owner: 'www-data', group: 'www-data', mount_options: ["dmode=775", "fmode=664"]`
to:
`config.vm.synced_folder ".", "/srv", nfs: true`
(I am on a Macbook Air running Yosemite). 
This greatly, greatly improved performance.  

Using wrk to test performance, I went from this:
Running 1m test @ http://my.dev.box
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.00us    0.00us   0.00us     nan%
    Req/Sec     0.00      0.00     0.00       nan%
  276 requests in 1.00m, 14.96MB read
  Socket errors: connect 0, read 0, write 0, timeout 224
Requests/sec:      4.59
Transfer/sec:    255.04KB

To this:
Running 1m test @ http://my.dev.box
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   235.12ms   26.12ms 253.59ms  100.00%
    Req/Sec    19.50      0.71    20.00    100.00%
  1771 requests in 1.00m, 95.57MB read
  Socket errors: connect 0, read 0, write 0, timeout 60
Requests/sec:     29.48
Transfer/sec:      1.59MB

See also:  https://stefanwrobel.com/how-to-make-vagrant-performance-not-suck

**Comment by westonruter** [comment]
I've implemented this for my team by adding the following to our team's `Customfile` (see our [feature branch](https://github.com/xwp/vip-quickstart/compare/feature/customfile) to add support for this):

```ruby
# Override synced folders with NFS if not on Windows
# via: https://github.com/Automattic/vip-quickstart/issues/372#issuecomment-73322521
if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) == nil
	config.vm.synced_folder ".", "/srv", nfs: true, owner: nil, group: nil, mount_options: nil
end

```

**Comment by joshbetz** [comment]
@westonruter I don't think you even need to detect Windows. Vagrant is supposed to fall back to Virtualbox shares if you're on Windows automatically. If you haven't had any problems, we should switch to NFS by default in Quickstart. I'd still like to use Rsync eventually, but there's nothing blocking us from using NFS in the meantime.

**Comment by westonruter** [comment]
The change is rolling out to our team. We're noticing huge performance improvements. I'll report back any problems. 

Another improvement with the above change is that scripts with the execute bit on the host machine are no longer getting clobbered inside of Vagrant (caused by `mount_options: ["dmode=775", "fmode=664"]`), meaning that we can again write `./my-script.sh` instead of `bash my-script.sh`.

**Comment by westonruter** [comment]
Here's an issue (a big one). When provisioning from scratch:

```
err: /Stage[main]//Nginx::Vhost[_]/File[/srv/www]/owner: change from 501 to www-data failed: Failed to set owner to '33': Operation not permitted - /srv/www
```

And then there are a bazillion (literally one *bazillion*) lines printed out like:

```
==> default: notice: /Stage[main]//File[/srv/www/wp-content/plugins]: Dependency File[/srv/www] has failures: true
==> default: warning: /Stage[main]//File[/srv/www/wp-content/plugins]: Skipping because of failed dependencies
==> default: notice: /File[/srv/www/wp-content/plugins/debug-bar-extender]: Dependency File[/srv/www] has failures: true
==> default: warning: /File[/srv/www/wp-content/plugins/debug-bar-extender]: Skipping because of failed dependencies
==> default: notice: /File[/srv/www/wp-content/plugins/debug-bar-extender/js]: Dependency File[/srv/www] has failures: true
==> default: warning: /File[/srv/www/wp-content/plugins/debug-bar-extender/js]: Skipping because of failed dependencies
```

And then when attempting to access <http://vip.local> I am presented with a MySQL error, which seems to be due to the provisioner failing from writing the `DB_PASSWORD` to `local-config.php`.

**Comment by westonruter** [comment]
Yeah, provisioning is not working, when I have:

```ruby
config.vm.synced_folder ".", "/srv", nfs: true
```

The result is:

![image](https://cloud.githubusercontent.com/assets/134745/6122423/54fc91e8-b147-11e4-80df-fee5d01e7f1d.png)

If I change this line to:

```ruby
config.vm.synced_folder ".", "/srv", nfs: true, owner: 'www-data', group: 'www-data'
```

Then I get an immediate Vagrant error:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* Shared folders that have NFS enabled do not support owner/group
attributes. Host path: .
```

So it seems in order for NFS to work, any provisioning logic which sets the file ownership is going to have to be disabled.

**Comment by westonruter** [comment]
So at the moment, the patch to enable NFS looks like it will have to include:

```patch
diff --git a/Vagrantfile b/Vagrantfile
index 83a74b6..f33e9e5 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -31,7 +31,11 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
     v.vm.box_url = "http://files.vagrantup.com/precise64_vmware.box"
   end
 
+  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) == nil
+    config.vm.synced_folder ".", "/srv", nfs: true, owner: 'www-data', group: 'www-data'
+  else
     config.vm.synced_folder ".", "/srv", owner: 'www-data', group: 'www-data', mount_options: ["dmode=775", "fmode=664"]
+  end
 
   # Address a bug in an older version of Puppet
   # See http://stackoverflow.com/questions/10894661/augeas-support-on-my-vagrant-machine
```

Followed by changes that prevent `chown`ing to `www-data` if NFS is enabled.

As a potential workaround, we could adjust the conditional to enable NFS to include not only if the user  is not on Windows, but also to prevent NFS if the user is provisioning. This would mean to provision and then have NFS enabled, they'd have to do:

```
vagrant destroy # if it exists
vagrant up --provision # NFS would have to be disabled
vagrant halt
vagrant up # now NFS will be enabled
```

However, there may be systems that are expecting files to be owned by `www-data` which will start failing. So again, I think we really need to disable any reference to `www-data` if NFS is enabled.

**Comment by paulschreiber** [comment]
Not only does provisioning not work under NFS, but neither does `bin/vip-init`. When I try that, I get the same failures as @westonruter:

    ==> default: err: /Vcsrepo[/srv/www/wp-content/themes/vip/plugins]/ensure: change from present to latest failed: Execution of '/usr/bin/svn --non-interactive switch -r 184616 https://vip-svn.wordpress.com/plugins/' returned 1: svn: E155005: No write-lock in '/srv/www/wp-content/themes/vip/plugins/thePlatform'
    ==> default: err: /Stage[main]//Nginx::Vhost[_]/File[/srv/www]/owner: change from 906720490 to www-data failed: Failed to set owner to '33': Operation not permitted - /srv/www

And 57,000+ lines of "Skipping because of failed dependencies" / "Dependency File[/srv/www] has failures: true".

**Comment by westonruter** [comment]
The `vip-init` calls `vagrant provision`, so that's to be expected.

**Comment by paulschreiber** [comment]
When I start up vagrant with NFS enabled, I see this auth prompt:

    ==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
    Password:

Is that expected?

**Comment by westonruter** [comment]
Yes: https://docs.vagrantup.com/v2/synced-folders/nfs.html

There are some instructions for how to get around this though.

**Comment by paulschreiber** [comment]
Here's what I see now with `vagrant up`:

```
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 10.86.73.1:'/Users/paul/.dev/quickstart' /srv

Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: mount to NFS server '10.86.73.1:/Users/paul/.dev/quickstart' failed: timed out, giving up
```

**Comment by paulschreiber** [comment]
I think my previous problem was due to a conflict between the 10.x IP range Quickstart uses and the one my VIPN uses. Disconnecting from the VPN and rebooting vagrant fixed it.

**Comment by paulschreiber** [comment]
I installed a brand new VM, set the RAM to 4096, the CPUs to 4 and switched to NFS. Cold load of home page was 38s. Warm load (refresh) was 16s. Opening an article page was 22s. Chrome shows TTFB (time to first byte) as 20.12 seconds. 

Something is causing a long stall before the page starts loading. Once the loading starts, it's done in under 2s.

**Comment by paulschreiber** [comment]
I found this tip: https://github.com/mitchellh/vagrant/issues/1807#issuecomment-19132198

```
	config.vm.provider "virtualbox" do |v|
		v.memory = 4096
		v.cpus = 4
	end
```

Chrome now loads the page in 5.11s (TTFB 5.07s). This is much better, but still not great.

**Comment by joshbetz** [comment]
@paulschreiber Do you want to submit a PR for `natdnshostresolver1` and `natdnsproxy1`?

**Comment by paulschreiber** [comment]
Enabling I/O APIC provided further improvement:
```
config.vm.provider "virtualbox" do |v|
  v.customize ["modifyvm", :id, "--ioapic", "on"]
end
```

Page loads are now 1.35s!

And one last fix via http://superuser.com/questions/850357/how-to-fix-extremely-slow-virtualbox-network-download-speed:
```
config.vm.provider "virtualbox" do |v|
  v.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
end
```

Page loads are now < 1.1s.

**Comment by paulschreiber** [comment]
PR: https://github.com/Automattic/vip-quickstart/pull/428

**Comment by paulschreiber** [comment]
Pull request submitted: https://github.com/Automattic/vip-quickstart/pull/429

**Comment by paulschreiber** [comment]
@joshbetz, can this be merged?

**Comment by paulschreiber** [comment]
Upgrading to VirtualBox 5.0.4 also seems to fix this problem.

**Comment by westonruter** [comment]
> Upgrading to VirtualBox 5.0.4 also seems to fix this problem.

@paulschreiber which problem? Performance in general with Quickstart? Even with out #429?

**Comment by paulschreiber** [comment]
Yes, 5.0.4 seems to have better networking performance by default without those change.

**Comment by westonruter** [comment]
My colleague @mehigh tested out VirtualBox 5 and noticed an improvement, but without the NFS patch it is still *much* slower than with the NFS patch.

**Comment by mehigh** [comment]
To add a little more detail on my test - this happened on a 2014 MBP running Yosemite 10.10.5. The page load time is consistently cut in half when the NFS patch is present as opposed to when it's not under VirtualBox 5.0.4 and Vagrant 1.7.4.

**Comment by paulschreiber** [comment]
I was using NFS with 5.0.4 as well. I ended up turning the NAT DNS changes back on because I was getting an empty `/etc/resolv.conf` without them.

**Comment by mikeschinkel** [comment]
@westonruter I have been battling with this issue for over 3 days (yes, over Xmas too.) I upgraded to El Capitan over Mavericks in hopes that would fix it but no dice.  I am now at the end of things to try so I'm hoping you can help.

I am getting is the same error you got back in Feb:

    ==> default: err: /Stage[main]//Nginx::Vhost[_]/File[/srv/www]/owner: change from 501 to www-data failed: Failed to set owner to '33': Operation not permitted - /srv/www

I am using your fix from the same day but it is not helping:

    config.vm.synced_folder ".", "/srv", nfs: true, mount_options: ["noatime"]

However, you said the following but I did not see any code to do it:

> _"Followed by changes that prevent chowning to www-data if NFS is enabled."_

Is that what I am missing?  And if so, mind if I ask how for me to go about it?  

Thanks in advance.

**Comment by joshbetz** [comment]
@mikeschinkel I recommend using the default VirtualBox shares. #429 was merged last week to help address performance.

**Comment by paulschreiber** [comment]
@mikeschinkel To update the VM, I disabled shared folders, rebooted, re-provisioned, re-enable shared folders, and rebooted again.

**Comment by mikeschinkel** [comment]
@joshbetz @paulschreiber Thanks for the help. 

Unfortunately after investing too much time trying to get this to work and running into one brick wall after another I've decided I will just build up a vagrant box from scratch and add what I need _(basically memcached and multisite)_ so I will be more able to debug problems if I build up one thing at a time.
