### ISSUE TITLE
Documentation refers to both vip.local and vip.dev as default hostnames during setup

### ISSUE THREAD

**Issue by bbttxu** [Automattic/vip-quickstart#376]
I was talking with someone and they mentioned it was vip.local now, and i said it was vip.dev. We went to the documentation and found we were both right! :) 

https://github.com/Automattic/vip-quickstart/blob/master/bin/vip-init refers to vip.dev. Is that still the default?

I'd submit a PR but it seems documentation isn't part of the repo anymore.

**Comment by joshbetz** [comment]
You actually are both right. Locally it is vip.local. On a staging site it is vip.dev by default, but you can change it to whatever you want.
