### ISSUE TITLE
wp-cli not working on new install.

### ISSUE THREAD

**Issue by brshewmaker** [Automattic/vip-quickstart#382]
Started up a new virtual machine with `vagrant up`, I pulled in my org's repo into themes/vip/mytheme and SSH'd in and tried to run `wp`, but it simply outputs nothing in the command prompt.  Looking at /var/log/syslog I see this:

```
Feb  6 22:06:43 vip php: PHP Fatal error:  Can't use method return value in write context in /srv/www/wp-content/plugins/vip-scanner/vip-scanner/class-wp-cli.php on line 131
Feb  6 22:06:43 vip php: PHP Stack trace:
Feb  6 22:06:43 vip php: PHP   1. {main}() /usr/bin/wp:0
Feb  6 22:06:43 vip php: PHP   2. include() /usr/bin/wp:4
Feb  6 22:06:43 vip php: PHP   3. include() phar:///usr/bin/wp/php/boot-phar.php:5
Feb  6 22:06:43 vip php: PHP   4. require() phar:///usr/bin/wp/php/wp-cli.php:26
Feb  6 22:06:43 vip php: PHP   5. include_once() phar:///usr/bin/wp/php/wp-settings-cli.php:197
```

If I simply comment out the code block, which is:
		 if ( ! empty( $scanner->get_errors() ) ) {
		 	$this->display_errors( $scanner, 'table' );
		 }
then `wp` works just fine.

Or, if I do a network disable of the VIP Scanner, then it also works fine.

**Comment by danielbachhuber** [comment]
This is the issue https://github.com/Automattic/vip-scanner/pull/240
