### ISSUE TITLE
Add Twig to wp-content/plugins directory

### ISSUE THREAD

**Issue by joshbetz** [Automattic/vip-quickstart#383]

**Comment by joshbetz** [comment]
This is on my list for today.

**Comment by joshbetz** [comment]
We need to install the v0.18.0 of the [Twig lib](https://github.com/twigphp/Twig/tree/master/lib/Twig) to wp-content/plugins, which is not version controlled. I guess we'll have to download it and move some files into place with Puppet.

**Comment by westonruter** [comment]
Not versioned? What about https://github.com/twigphp/Twig/releases/tag/v1.18.0

**Comment by joshbetz** [comment]
@westonruter I don't really have a good plan for how we're going to get this into Quickstart. Given that the plugins directory is unversioned, you may have to drop v0.18.0 of the [Twig library](https://github.com/twigphp/Twig/tree/master/lib/Twig) into the plugins directory for now.

**Comment by westonruter** [comment]
@joshbetz why not just add it to the `$github_plugins` array in [`puppet/manifests/sections/wp.pp`](https://github.com/Automattic/vip-quickstart/blob/126909ad7a32599789b4037888f7edbcb8da5d21/puppet/manifests/sections/wp.pp#L15-L22)?

**Comment by joshbetz** [comment]
I don't think we can specify subdirectories. We only have the `lib/Twig` subdirectory installed.

**Comment by matthewspencer** [comment]
@joshbetz Does this mean that Twig will be added to VIP?

**Comment by joshbetz** [comment]
Twig support on WordPress.com is looking unlikely again. Closing this for now.
