### ISSUE TITLE
wp import command is failed silently

### ISSUE THREAD

**Issue by umbrella-mikhail-menshinskiy** [Automattic/vip-quickstart#389]
Hello.
I'm not sure if it's a problem with vip-quickstart or not, but when I'm trying to import the file by using `wp import` command it imports 4 posts and stops silently: no errors, no warnings ...

I have increased the memory up to 3Gb, but it doesn't help.
I have run the `wp import` with `--debug` option but it still fails.

Do you have any ideas how can I find the reason?

**Comment by joshbetz** [comment]
What does the PHP error log look like?

**Comment by umbrella-mikhail-menshinskiy** [comment]
Sorry, but where can I find these logs?

**Comment by umbrella-mikhail-menshinskiy** [comment]
I have found the problem.
We should add the following to the local-config.php `define('WP_MAX_MEMORY_LIMIT', '2048M');`
