### ISSUE TITLE
Sync: attachments aren't in SQL dump

### ISSUE THREAD

**Issue by mboynes** [Automattic/vip-quickstart#391]
Admittedly, it's been a few months since I last tried QS Sync, so if this has since been resolved, sorry for the superfluous issue.

When QS Sync gets the SQL dump, attachments are missing from the data. That data is still valuable, even though the media wouldn't actually be downloaded. It's very easy to leverage existing attachment filters to refer to the images on the WordPress.com CDN (which is exactly the same way Jetpack/Photon works).

**Comment by mboynes** [comment]
@joshbetz is this something that's going to be possible, and if so, any ETA on it? If it could happen within the next week it would really be a huge help for me.

**Comment by cohix** [comment]
Hey, we tested the current sync implementation against some test sites, and the attachments seem to sync properly. Is there any more info you could provide? What site you're syncing, what kinds of attachments aren't being included, etc?

**Comment by mboynes** [comment]
Thanks @cohix, I'll check it out. Like I said, I haven't tried it in a while, so it's possible it's since been resolved. I'm giving it a shot right now and I'll report back!

**Comment by cohix** [comment]
Sounds good! You should also know that I'm working on revamping sync to be much more robust, so you'll have a much better sync in a few weeks.

**Comment by mboynes** [comment]
Hey @cohix, I checked out quickstart fresh, checked out the 'dashboard' branch, "synced" a site, and attachments were not included in the posts table. I grabbed the raw sql from the /tmp/ dir and sure enough, they weren't in there.

Since the SQL export is an API call, perhaps it's an API permissions difference?

**Comment by mboynes** [comment]
@cohix did you get anywhere with this, or were you at least able to replicate the missing attachments issue?

**Comment by cohix** [comment]
@mboynes I haven't been able to reproduce that issue, but the new QS sync will be ready in the near future, so hopefully it will help! If you have any specifics (i.e. the vip site you're trying to sync, etc) that would help me potentially reproduce the issue

**Comment by nschoenholtz** [comment]
Just a bump on this -- I just tried this yesterday and still received 0 attachments in the raw sql file.
