### ISSUE TITLE
Debug notices in exported WXR file

### ISSUE THREAD

**Issue by david-binda** [Automattic/vip-quickstart#392]
I've noticed following warnings being prepended to the XML itself: 

```
Notice: Undefined offset: 0 in /srv/www/wp-content/plugins/query-monitor/Backtrace.php on line 155
Notice: Undefined index: line in /srv/www/wp-content/plugins/query-monitor/Backtrace.php on line 158
```

The file: https://gist.github.com/david-binda/c95e1b690dcd2427115f

**Comment by joshbetz** [comment]
@david-binda Can you submit a PR on the query-monitor repo that fixes this? https://github.com/johnbillion/query-monitor

**Comment by david-binda** [comment]
roger that @joshbetz - thanx
