### ISSUE TITLE
Don't run trunk for staging environments, only beta releases

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/vip-quickstart#393]
Suggestion from core https://wordpress.slack.com/archives/core/p1424990017000197

**Comment by nacin** [comment]
That was not what was suggested in the linked message.

Trunk should absolutely be the default in a staging/testing environment.

Developers should know how to not use trunk, or to revert individual commits, when it is appropriate to do so.

**Comment by pento** [comment]
In addition to @nacin's comment, WP.com has never been 100% in sync with WP trunk, though we're moving closer.

Reports of where they differ in a broken way are appreciated, but changing Quickstart from using WP trunk isn't an option.
