### ISSUE TITLE
Javascript not loading

### ISSUE THREAD

**Issue by developdaly** [Automattic/vip-quickstart#400]
jQuery and other Javascript are not loading. I'm still troubleshooting this and it's likely more related to WordPress trunk than Quickstart, but since last night all Quickstart installs we have are crashing and from the dashboard we're getting these console errors below. Another possibility is permissions on `load-scripts.php`. Still looking.

```
GET http://vip.local/wp-admin/load-scripts.php?c=0&load%5B%5D=jquery-core,jquery-migrate,utils&ver=4.2-alpha-31752 
index.php:391 GET http://vip.local/wp-admin/load-scripts.php?c=0&load%5B%5D…nstall,svg-painter,heartbeat,wp-au&load%5B%5D=th-check&ver=4.2-alpha-31752 

vip-scanner-async.js?ver=4.2-alpha-31752:4 Uncaught ReferenceError: jQuery is not defined
```

**Comment by mauteri** [comment]
Having the same issue.

**Comment by danielbachhuber** [comment]
It's a core issue https://wordpress.slack.com/archives/core/p1426174568004078

**Comment by joshbetz** [comment]
Thanks for verifying, @danielbachhuber
