### ISSUE TITLE
Error: Call to undefined method Debug_Bar_Panel::Debug_Bar_Panel

### ISSUE THREAD

**Issue by westonruter** [Automattic/vip-quickstart#407]
We've been starting to notice a fatal error after provisioning Quickstart on an EC2 instance:

> Error: Call to undefined method Debug_Bar_Panel::Debug_Bar_Panel() (type: 1, line: 65, file: /srv/www/wp-content/plugins/log-viewer/includes/class-dbpanel.php)

The only solution we've found so far is to just remove `log-viewer` entirely:

```
mv /srv/www/wp-content/plugins/log-viewer /srv/www/wp-content/plugins/log-viewer.disabled
```

**Comment by joshbetz** [comment]
Already fixed in https://github.com/Automattic/vip-quickstart/commit/732649cda18da265ae64c393f34a912869614292 and https://github.com/Automattic/vip-quickstart/commit/a2f710ee0d58aeb87a027390777549f69ffb4f6d
