### ISSUE TITLE
really slow on macbook

### ISSUE THREAD

**Issue by showcasefloyd** [Automattic/vip-quickstart#410]
Any tips to speed this up? I'm trying to work on a plug in, but it's painfully slow.

**Comment by joshbetz** [comment]
Dupe of #372

**Comment by westonruter** [comment]
@showcasefloyd this NFS workaround is what me and my colleagues have been using to make the speed bearable: https://github.com/Automattic/vip-quickstart/issues/372#issuecomment-73650663

**Comment by showcasefloyd** [comment]
I'm trying it now. But for some reason the vip.local is now coming up 404
