### ISSUE TITLE
Configuration problem on server

### ISSUE THREAD

**Issue by steioria** [Automattic/vip-quickstart#415]
Hi, 
I'm trying to setup my vip quickstart enviroment on a virtual server running CentOS 7.

After Installing Puppet and Git, and cloned the repo, as mentioned here:
https://vip.wordpress.com/documentation/quickstart/#public-server

I tried to: 

sudo /srv/bin/vip-init --server

but I received the following errors:

which: no wp in (/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)

and also:

Sorry, user root is not allowed to execute '/usr/bin/whoami' as root on dev-wordpress-vip.

Thoughts? I'm not an expert, so any help will be appreciate! thank you!

**Comment by joshbetz** [comment]
Ubuntu 12.04 is required for Quickstart.
