### ISSUE TITLE
Unable to successfully Vagrant up (vagrant version: 1.7.2)

### ISSUE THREAD

**Issue by zachwills** [Automattic/vip-quickstart#417]
Hey all,

I ran the command from the [Getting Started](https://vip.wordpress.com/documentation/quickstart/) guide:

`git clone --recursive https://github.com/Automattic/vip-quickstart.git` 

Then I `cd vip-quickstart` and `vagrant up` just like the instructions say to, but I run into the following error:

`==> default: Invalid parameter submodules at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/sections/gitplugin.pp:13 on node vip.riotgames.com`

`The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

If it helps, my Vagrant version is 1.7.2, and my Virtualbox version is 4.3.4. I did some searching around and I couldn't find the error I was getting anywhere, and the fixes that worked for others with `vagrant up` issues didn't work here. (I also tried `bin/vip-init`).

Any thoughts as to whats going wrong?

**Comment by jjeaton** [comment]
Issue appears to be caused by this recent commit: https://github.com/Automattic/vip-quickstart/commit/67e6f4e0911066977669ad2e6893fc49310e2292

**Comment by zachwills** [comment]
It appears so! I went ahead and commented out the line that was added in that commit and ran `vagrant provision` and it worked like a charm.

Thanks @jjeaton!

**Comment by zachwills** [comment]
Reopened since @jjeaton's fix is a bandaid and the source needs to be addressed

**Comment by danielbachhuber** [comment]
https://github.com/Automattic/vip-quickstart/pull/413#issuecomment-88992496
