### ISSUE TITLE
Provisioning error on server: skipping because of failed dependencies

### ISSUE THREAD

**Issue by steioria** [Automattic/vip-quickstart#422]
Hi, I'm trying to run:

sudo /srv/bin/vip-init --server

on a server running Ubuntu 12.04 after installing git, puppet and cloning this git repository.

I'm receiving several warning for "skipping because of failed dependencies", and the provision fails after about 20 second.

Here's the complete output:

https://gist.github.com/steioria/1316f34dabd691db6ff8

after then, I tried to delete, clone again, git submodule update before provisioning, and still having this problem..

Any help?

Thank you

**Comment by zamoose** [comment]
Looks like Subversion didn't install cleanly. Is the `svn` binary available
after the initial provisioning? In that case, try re-provisioning (`vagrant
provision` or `vagrant up --provision`).

On Mon, Apr 13, 2015 at 4:48 AM, Ste <notifications@github.com> wrote:

> Hi, I'm trying to run:
>
> sudo /srv/bin/vip-init --server
>
> on a server running Ubuntu 12.04 after installing git, puppet and cloning
> this git repository.
>
> I'm receiving several warning for "skipping because of failed
> dependencies", and the provision fails after about 20 second.
>
> Here's the complete output:
>
> https://gist.github.com/steioria/1316f34dabd691db6ff8
>
> after then, I tried to delete, clone again, git submodule update before
> provisioning, and still having this problem..
>
> Any help?
>
> Thank you
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/vip-quickstart/issues/422>.
>



-- 
-Doug

**Comment by steioria** [comment]
Hi @zamoose, 

yes the svn is in place and seems to work fine. I've also tried to apt-get install it separately, and try to reprovision, but no luck. 
Btw I'm on a server with Ubuntu 12.04, and i followed these guidelines for the installation:

Public Server #

- Add user with SSH key
- Install Puppet and Git
- git clone --recursive https://github.com/Automattic/vip-quickstart.git /srv
- sudo /srv/bin/vip-init --server [--domain=<domain>]

There isn't any mention to install vagrant separately in this kind of enviroment. I am wrong?
Thanks anyway for the help :)

**Comment by zamoose** [comment]
Bah, whiffed on that fact. Yeah, no Vagrant necessary there.

Can you try a manual Puppet provision with the verbosity turned up? I used
to use `puppet -todv` to get crazy debug spam output. Then we can see why
the svn step is tossing a 1 instead of a 0. (This signals to Puppet that
the step went awry and thus everything marked as a dependency fails.)

On Mon, Apr 13, 2015 at 9:49 AM, Ste <notifications@github.com> wrote:

> Hi @zamoose <https://github.com/zamoose>,
>
> yes the svn is in place and seems to work fine. I've also tried to apt-get
> install it separately, and try to reprovision, but no luck.
> Btw I'm on a server with Ubuntu 12.04, and i followed these guidelines for
> the installation:
>
> Public Server #
>
>    - Add user with SSH key
>    - Install Puppet and Git
>    - git clone --recursive
>    https://github.com/Automattic/vip-quickstart.git /srv
>    - sudo /srv/bin/vip-init --server [--domain=]
>
> There isn't any mention to install vagrant separately in this kind of
> enviroment. I am wrong?
> Thanks anyway for the help :)
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/vip-quickstart/issues/422#issuecomment-92360601>
> .
>



-- 
-Doug

**Comment by steioria** [comment]
looking at the vip-init file the puppet instruction is this one:

puppet apply --modulepath=/srv/puppet/modules --templatedir=/srv/puppet/files /srv/puppet/manifests/init.pp

I added --verbose --debug --detailed-exitcodes (reading some documentation here: https://docs.puppetlabs.com/references/3.6.latest/man/apply.html)

the output now is (of course) bigger:

https://gist.github.com/steioria/bb030defc793fa7b31cb


maybe the problem is here?

info: /Vcsrepo[/srv/www/wp-content/themes/vip/plugins]: Provider svn does not support features multiple_remotes; not managing attribute remote
info: /Vcsrepo[/srv/www/wp-content/themes/pub/twentyfourteen]: Provider svn does not support features multiple_remotes; not managing attribute remote
info: /Vcsrepo[/srv/www/wp]: Provider svn does not support features multiple_remotes; not managing attribute remote
info: /Vcsrepo[/srv/www/wp-tests]: Provider svn does not support features multiple_remotes; not managing attribute remote

Thanks again!

**Comment by steioria** [comment]
Adding logoutput => on_failure inside subversion.pp, I have found that the tty enabled was causing these problems. Disabled the tty inside sudoers and now the provisioning seems to work fine.
