### ISSUE TITLE
Path to theme folder on QS doesn't match path on VIP

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/vip-quickstart#425]
The path to your theme folder on Quickstart doesn't match the path on VIP:

On our (10up's) QuickStart staging server:

    /wp-content/themes/pub/fivethirtyeight/assets/js/vendor/popcorn.js

On VIP:

    /wp-content/themes/vip/espn-fivethirtyeight/assets/js/vendor/popcorn.js

This means you can't (easily) code relative paths in JS, as one has */pub/* and one has */vip/* in the path.

**Comment by danielbachhuber** [comment]
You can use `plugin_url( 'relative/path/inside/theme.js', __file__ )` inside your theme.

**Comment by paulschreiber** [comment]
In my case, I needed the path inside a `js` file, not a PHP one. Regardless, it still seems like a bug.

**Comment by danielbachhuber** [comment]
> In my case, I needed the path inside a JS file, not a PHP one.

You can register the path to a variable using `wp_localize_script()`

>  Regardless, it still seems like a bug.

If your theme is located in `/wp-content/themes/pub/fivethirtyeight`, then 10up misconfigured your Quickstart server.

**Comment by paulschreiber** [comment]
Yes, I could set a path with `wp_localize_script()` or devise other workarounds.

Are you saying */vip/* should be in the path for 10up's server as well? If so, I'll check with 10up about their config.

**Comment by mdrovdahl** [comment]
Indeed. To be consistent with wp.com (prod), your path to (VIP) theme needs to be:
`/wp-content/themes/vip/fivethirtyeight/`
