### ISSUE TITLE
install svn-bisect by default

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/vip-quickstart#426]
Install svn-bisect by default.
http://search.cpan.org/dist/App-SVN-Bisect/bin/svn-bisect

This is very handy for tracking down when something broke in WordPress.

```
$ cpan
cpan> install App:SVN::Bisect
```

**Comment by joshbetz** [comment]
I recommend installing this via a personal Vagrantfile in `~/.vagrant.d`. You can see the load order for Vagrantfiles here: http://docs.vagrantup.com/v2/vagrantfile/
