### ISSUE TITLE
Non-admin memory limit (WP_MEMORY_LIMIT) not specified

### ISSUE THREAD

**Issue by westonruter** [Automattic/vip-quickstart#433]
We're increasingly getting memory limit errors such as:

> PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate X bytes) in /srv/www/wp/wp-includes/functions.php on line 384

I notice in `wp-config.php` that we have:

```
define( 'WP_MAX_MEMORY_LIMIT', '1024M' );
```

However, there is no `WP_MEMORY_LIMIT` defined. The max version is defined as the limit in the WP admin, with the later applying elsewhere: https://github.com/xwp/wordpress-develop/blob/8bf3003c67bf78ed3b5a1cfa13a881fbcda77ad0/src/wp-includes/default-constants.php#L47-L52

What is the non-admin memory limit on WordPress.com? Is it 128M PHP default?

**Comment by joshbetz** [comment]
512M

**Comment by westonruter** [comment]
It turns out that the memory limits on WordPress.com are actually much less:

```
WP_MAX_MEMORY_LIMIT: 256M
WP_MEMORY_LIMIT: 64M
```

Whereas in Quickstart they are:

```
WP_MAX_MEMORY_LIMIT: 1024M
WP_MEMORY_LIMIT: 512M
```

See Zendesk 41969.

**Comment by philipjohn** [comment]
I'm going to re-open this for discussion.

Pinging @joshbetz
