### ISSUE TITLE
Ooyala plugin broken with latest updates

### ISSUE THREAD

**Issue by stevegrunwell** [Automattic/vip-quickstart#437]
There were some updates made today to the Ooyala VIP plugin which seem to remove the `Ooyala_Video` class, causing "PHP Fatal error:  Class 'Ooyala_Video' not found..." errors in the logs.

It looks like there were three commits made related to Ooyala today:

```
------------------------------------------------------------------------
r201559 | davidbinovec | 2015-06-10 17:53:35 +0000 (Wed, 10 Jun 2015) | 4 lines

Ooyala: update the plugin to 2.0.2 as it was tested in the release candidate repository

/z 39063

------------------------------------------------------------------------
r201442 | davidbinovec | 2015-06-10 10:09:25 +0000 (Wed, 10 Jun 2015) | 2 lines

Ooyala: applying patch sent us via /z 39063

------------------------------------------------------------------------
r201258 | davidbinovec | 2015-06-09 15:46:59 +0000 (Tue, 09 Jun 2015) | 2 lines

Ooyala: applying patch set via /z 39063
```

I'm having some difficulty viewing the specific of those commits, but we just noticed today that Ooyala was broken on our development and staging servers (both running VIP Quickstart).

**Comment by david-binda** [comment]
Hey @stevegrunwell 

Thank you for reporting that. I reverted that change in production on WordPress.com VIP platform. The new version of the plugin is available as a release candidate as well and can be loaded via `wpcom_vip_load_plugin( 'ooyala', 'plugins', true );`

We're planning to update the plugin in the production soon, so if you could test and adapt the theme's code to the release candidate (as that one can be used in production as well), it would be awesome.

Ping me in case you need assistance.

**Comment by stevegrunwell** [comment]
@david-binda,

Awesome, thank you for being so responsive. I'll have someone from my team test against the release candidate and let you know if we run into any trouble.

Thanks again!
