### ISSUE TITLE
Oembed/Wistia not working in wp-admin

### ISSUE THREAD

**Issue by bschneidewind** [Automattic/vip-quickstart#442]
Noticed that support for the oembed/wistia dropped off recently - old posts seem to work fine but new posts do not display the embed correctly.

**Comment by joshbetz** [comment]
@bschneidewind Are you having the same problem in production?

**Comment by imaginegrafix** [comment]
No, it is working in production.

**Comment by bschneidewind** [comment]
@joshbetz - Yeah, it seems to work in production (although the preview in wp-admin doesn't work correctly - the output on the front end is correct) Example: http://chryslercapital.com/a-new-vid-test-page

**Comment by bschneidewind** [comment]
Looks like the updates to quickstart have resolved this issue
