### ISSUE TITLE
The called constructor method for WP_Widget is deprecated since version 4.3.0

### ISSUE THREAD

**Issue by developdaly** [Automattic/vip-quickstart#443]
This isn't a Quickstart issue, so I expect you to close this, but the notice shows in Quickstart environments and is forced by Quickstart.

> ( ! ) Notice: The called constructor method for WP_Widget is deprecated since version 4.3.0! Use `__construct()` instead. in `/srv/www/wp/wp-includes/functions.php` on line 3456.

See line 26: https://vip-svn.wordpress.com/plugins/vip-do-not-include-on-wpcom/vip-powered-wpcom/vip-powered-wpcom.php

Use `parent::__construct()` instead of `$this->WP_Widget()`.

**Comment by joshbetz** [comment]
Hey @developdaly, can you open a ticket with VIP support?

**Comment by westonruter** [comment]
I have a Zendesk ticket opened as well (42392), with patches.

**Comment by mammutka** [comment]
I would appreciate an answer because I have the same problem... How did you solve it?

Thanks, Tanja

**Comment by westonruter** [comment]
@mammutka here are the patches I provided VIP: https://gist.github.com/westonruter/97c6017f9be6a472e098

**Comment by westonruter** [comment]
This duplicates #449.

**Comment by keron097** [comment]
Here is the solution
First find $this->WP_Widget from your directory. For this you can use Find in Files in windows. Find $this->WP_Widget, select your directory and then click on Find All.
 
![findinfiles](https://cloud.githubusercontent.com/assets/15084592/10422984/777e60a0-70e3-11e5-97fd-7259dda73650.PNG)

After that select that file/files where $this->WP_Widget( found and replace with parent::__construct( . I think your error will be solved. 
Enjoy It.
Thank you.
