### ISSUE TITLE
Include elasticsearch in quickstart

### ISSUE THREAD

**Issue by rinatkhaziev** [Automattic/vip-quickstart#444]
It'd be really helpful to be able to run elasticsearch on quickstart to avoid pain with testing any ES-based functionality.

Here's puppet module for that:

https://github.com/elastic/puppet-elasticsearch

**Comment by joshbetz** [comment]
Hey Rinat! Elasticsearch can actually be tested via the REST API. If you open a ticket with VIP Support, we'll be happy to walk you through that.
