### ISSUE TITLE
Not seeing PHP warnings and notices 

### ISSUE THREAD

**Issue by keithwi** [Automattic/vip-quickstart#451]
I recently got a fresh copy of quickstart and was making a WP plugin. I do see PHP errors but I don't see any warnings or notices. I did SSH into the virtual machine and changed the `error_reporting` to `E_ALL` but still no luck. Any clues?

**Comment by johnciacia** [comment]
Duplicate of #404?

**Comment by keithwi** [comment]
Yes it is. Thanks

**Comment by keithwi** [comment]
Any fix for this other than editing the plugin? The suggested workaround doesnt work for me (https://gist.github.com/westonruter/187da1b14f0149243fd0)

**Comment by joshbetz** [comment]
Let's track this in #404
