### ISSUE TITLE
WPCOM_VIP_CLI_Command class does not exist

### ISSUE THREAD

**Issue by johnbillion** [Automattic/vip-quickstart#456]
WordPress.com VIP's documentation states that WP-CLI commands should extend the `WPCOM_VIP_CLI_Command` class instead of the `WP_CLI_Command` class.

The `WPCOM_VIP_CLI_Command` class doesn't exist in Quickstart, which means it's not possible for our commands to extend this class on our development environment, nor use its `stop_the_insanity()` method.

**Comment by david-binda** [comment]
Thank you for reporting that @johnbillion 

I'll have a look into it. In a mean time, here's a code of said class:

```
<?php

class WPCOM_VIP_CLI_Command extends WP_CLI_Command {

	/**
	 * Clear all of the caches for memory management
 	 */
	protected function stop_the_insanity() {
		/**
		 * @var \WP_Object_Cache $wp_object_cache
		 * @var \wpdb $wpdb
		 */
		global $wpdb, $wp_object_cache;

		$wpdb->queries = array(); // or define( 'WP_IMPORTING', true );

		if ( is_object( $wp_object_cache ) ) {
			$wp_object_cache->group_ops = array();
			$wp_object_cache->stats = array();
			$wp_object_cache->memcache_debug = array();
			$wp_object_cache->cache = array();

			if ( method_exists( $wp_object_cache, '__remoteset' ) ) {
				$wp_object_cache->__remoteset(); // important
			}
		}
	}

}
```

**Comment by westonruter** [comment]
@johnbillion it should be located in the vip/plugins repo. Look under: `/srv/www/wp-content/themes/vip/plugins/vip-do-not-include-on-wpcom/vip-wp-cli.php`

SVN source: https://vip-svn.wordpress.com/plugins/vip-do-not-include-on-wpcom/vip-wp-cli.php

This repo should be getting cloned into your Quickstart via: https://github.com/Automattic/vip-quickstart/blob/0e54800664d4b6399ff8a0bd9e5adecbe85b6528/puppet/manifests/sections/wp.pp#L109-L113

**Comment by david-binda** [comment]
@johnbillion yup, @westonruter is correct. I've just tested the presence of `WPCOM_VIP_CLI_Command` class and it's only method in a fresh install of the Quickstart and it is present.

You might just need to `git pull` and `vagrant provision` in order to update your Quickstart.

I'm closing this issue as invalid.
