### ISSUE TITLE
Jetpack 3.6.1 Causes Permissions Error

### ISSUE THREAD

**Issue by freakingid** [Automattic/vip-quickstart#457]
I just pulled / setup a new VIP QS instance yesterday 9/4, and get the "You do not have sufficient permissions to access this page" error when trying to get in to wp-admin.

I've traced it to Jetpack version 3.6.1, something to do with more permissions checks.

I haven't had time to figure this out yet, but wanted to get an issue in here and say that for now I'm moving forward by substituting Jetpack 3.6.0 plugin instead.

**Comment by joshbetz** [comment]
See #455
