### ISSUE TITLE
Use WP-CLI nightly

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/vip-quickstart#466]
It's stable enough for local development use, and will help prevent Quickstart users running WordPress trunk from getting bit by breaking issues like https://github.com/wp-cli/wp-cli/pull/2118

I think https://github.com/joshbetz/puppet-wp may need to be updated to support stable _or_ nightly.

**Comment by joshbetz** [comment]
:+1:

**Comment by westonruter** [comment]
Note that WP-CLI on WordPress.com is still at an old version, AFAIK. So using trunk in Quickstart wouldn't be good for WPCOM-compat, though not any worse than using stable right now.
