### ISSUE TITLE
Can we upgrade Ubuntu and/or packages?

### ISSUE THREAD

**Issue by jamesmehorter** [Automattic/vip-quickstart#468]
I'm curious to know what the current VIP production server(s) are running for software.

Are they running Ubuntu Precise (v12) like we are in VIPQS? I see that Ubuntu Trusty (v14) is the current stable.

What about Nginx? VIPQS is currently running 1.1.19, though 1.8.0 is the current stable.

How often are packages upgraded on production? I.e. when can/should we be running apt-get update/upgrade in VIPQS?

Thanks!

**Comment by mdrovdahl** [comment]
Hi James,

We recommend not mucking about below the WP (application) layer in QS. It's not an exact replica of production (eg: prod uses debian), but it's also setup purposefully as is.

Are you encountering a specific issue that you expect an apt-get update/upgrade would resolve? If so, please open a ticket within the VIP support portal.

Cheers,
Mark D
