### ISSUE TITLE
WordPress coding standards fail to install

### ISSUE THREAD

**Issue by philipjohn** [Automattic/vip-quickstart#471]
When running VIP Scanner, it gives this error:

> The WordPress standard for PHP CodeSniffer is not installed
> The WordPress Coding Standard (WordPress) for PHP CodeSniffer is not installed. No code sniffing will be performed. Please see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards for information.

Puppet [tries to install the WordPress Coding Standards](https://github.com/Automattic/vip-quickstart/blob/master/puppet/manifests/sections/php.pp#L50) but when VIP Scanner executes `phpcs -i` the output doesn't include WordPress:

```
The installed coding standards are PSR2, Squiz, PSR1, Zend, MySource, PHPCS and PEAR
```

I can see the standards sitting at `/usr/share/php/PHP/CodeSniffer/Standards/WordPress` so Puppet does get them there;

```
-rw-r--r--  1 root root 6808 Jun 22 16:21 CHANGELOG.md
-rw-r--r--  1 root root  779 Jun 22 16:21 composer.json
-rw-r--r--  1 root root 5045 Jun 22 16:21 CONTRIBUTING.md
drwxr-xr-x  8 root root 4096 Jun 22 16:21 .git/
-rw-r--r--  1 root root   52 Jun 22 16:21 .gitignore
-rw-r--r--  1 root root 1096 Jun 22 16:21 LICENSE
-rw-r--r--  1 root root 1355 Jun 22 16:21 project.ruleset.xml.example
-rw-r--r--  1 root root 5873 Jun 22 16:21 README.md
-rw-r--r--  1 root root 1003 Jun 22 16:21 .travis.yml
drwxr-xr-x  4 root root 4096 Jun 22 16:21 WordPress/
drwxr-xr-x  2 root root 4096 Jun 22 16:21 WordPress-Core/
drwxr-xr-x  2 root root 4096 Jun 22 16:21 WordPress-Docs/
drwxr-xr-x  2 root root 4096 Jun 22 16:21 WordPress-Extra/
drwxr-xr-x  2 root root 4096 Jun 22 16:21 WordPress-VIP/
```

Clearly that isn't connecting up with PHPCS.

It can be fixed manually from within the vm with:
```
$ sudo phpcs --config-set installed_paths /usr/share/php/PHP/CodeSniffer/Standards/WordPress
Config value "installed_paths" added successfully
$ phpcs -i
The installed coding standards are PSR2, Squiz, PSR1, Zend, MySource, PHPCS, PEAR, WordPress-Core, WordPress-Docs, WordPress-VIP, WordPress-Extra and WordPress
```

We perhaps just need an extra command block in php.pp to connect those dots?

**Comment by westonruter** [comment]
It looks like Quickstart is cloning the repo in to the PHP_CodeSniffer directory tree in a way that would have only worked for a very old version of WordPress-Coding-Standards, before we re-organized the standards into one repo.

For how to install the standards, you can re-use what is [used in VVV](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/d91c277d5cffaffd679e95b15e1e96217093e6f5/provision/provision.sh#L586-L589), which is the same as shown above. Additionally, the default coding standard can also be set:

```sh
phpcs --config-set default_standard WordPress-VIP
```

**Comment by iamjohnford** [comment]
I ran into the same issue as #475 where it didn't install properly.

Looks like there might be a bug in `php-pear`? Running `sudo apt-get install php-pear` and then `sudo /usr/bin/pear upgrade -a pear.php.net/PHP_CodeSniffer` fixed the "not a valid package archive" error for me.
