### ISSUE TITLE
Log Deprecated Notices plugin is throwing Warnings

### ISSUE THREAD

**Issue by david-binda** [Automattic/vip-quickstart#484]
And those warning as causing the Jetpack's "Reindex posts" button on debug screen not working:

<img width="648" alt="screen-shot-2015-12-11-at-16-20-27" src="https://cloud.githubusercontent.com/assets/3651036/11748308/ed337a10-a027-11e5-9758-27876e2f5582.png">

<img width="648" alt="screen-shot-2015-12-11-at-16-20-34" src="https://cloud.githubusercontent.com/assets/3651036/11748314/f16f75de-a027-11e5-8b78-c766db9b5473.png">

Here's a quick patch which might need more testing: https://gist.github.com/david-binda/4ed499e1f6183eaaf2bf

**Comment by david-binda** [comment]
There's a trac ticket for this now: https://plugins.trac.wordpress.org/ticket/2464 opened by @paulschreiber

**Comment by westonruter** [comment]
See also https://github.com/johnbillion/query-monitor/pull/157

**Comment by joshbetz** [comment]
Closing in favor of the query monitor issue.

**Comment by paulschreiber** [comment]
@joshbetz I think it'd be good to take both patches — the plugin should be more resilient in the face of others' bad code.

**Comment by joshbetz** [comment]
@paulschreiber sure, I just meant that it's not specific to Quickstart.
