### ISSUE TITLE
PHP Codesniffer Error when loading

### ISSUE THREAD

**Issue by escobar022** [Automattic/vip-quickstart#489]
With this current iteration, I ran into an issue when trying to use PHP Codesniffer remotely.

After vagrant up && vagrant ssh into the box, using phpcs on the cmd line:
$ phpcs 
Failed loading /usr/lib/php5/20090626+lfs/xdebug.so:  /usr/lib/php5/20090626+lfs/xdebug.so: cannot open shared object file: No such file or directory

I looked to see if this folder existed, and it didnt. 

After looking for an hour, I was able to find this being required in :
nano /etc/php5/conf.d/20-xdebug.ini :
zend_extension=/usr/lib/php5/20090626+lfs/xdebug.so

I was able to find that this file is actually here /usr/lib/php5/20131226/xdebug.so and updated the file above. 

I know this is a patch more than a fix. Was wondering if anyone knew what could be causing this.

**Comment by joshbetz** [comment]
See #485
