### ISSUE TITLE
Fresh install failing

### ISSUE THREAD

**Issue by mdrovdahl** [Automattic/vip-quickstart#500]
Steps to reproduce:
* start with a fresh install
* vagrant destroy and rm-rf vip-quickstart any previous installation
* git clone --recursive https://github.com/Automattic/vip-quickstart.git
* vagrant up  

Process completes with a running VM, but WP is not fully installed. From the install log:

==> default: notice: /Vcsrepo[/srv/www/wp]/ensure: Creating repository from latest
==> default: notice: /Vcsrepo[/srv/www/wp]/ensure: created
==> default: err: /Stage[main]//Wp::Site[/srv/www/wp]/Exec[wp install /srv/www/wp]/returns: change from notrun to 0 failed: /usr/bin/wp core multisite-install --url='vip.local' --title='vip.local' --admin_email='admin@example.com' --admin_name='wordpress' --admin_password='wordpress' returned 255 instead of one of [0] at /tmp/vagrant-puppet-3/modules-0/wp/manifests/site.pp:30

**Comment by mdrovdahl** [comment]
within the VM:

 vagrant@vip:/srv/www/wp$ wp
PHP Fatal error:  Call to undefined function apply_filters() in /srv/www/wp/wp-includes/load.php on line 315
PHP Stack trace:
PHP   1. {main}() /usr/local/src/wp-cli/bin/wp:0
PHP   2. include() /usr/local/src/wp-cli/bin/wp:4
PHP   3. include() phar:///usr/local/src/wp-cli/bin/wp/php/boot-phar.php:5
PHP   4. WP_CLI\Runner->start() phar:///usr/local/src/wp-cli/bin/wp/php/wp-cli.php:21
PHP   5. WP_CLI\Runner->load_wordpress() phar:///usr/local/src/wp-cli/bin/wp/php/WP_CLI/Runner.php:755
PHP   6. require() phar:///usr/local/src/wp-cli/bin/wp/php/WP_CLI/Runner.php:807
PHP   7. WP_CLI\Utils\wp_debug_mode() phar:///usr/local/src/wp-cli/bin/wp/php/wp-settings-cli.php:59
PHP   8. wp_debug_mode() phar:///usr/local/src/wp-cli/bin/wp/php/utils-wp.php:22

**Comment by deltamualpha** [comment]
Same here. Seems like a bug in wp-cli: https://github.com/wp-cli/wp-cli/issues/2953

**Comment by mdrovdahl** [comment]
Good spot. https://core.trac.wordpress.org/changeset/37626 seems maybe the culprit?

**Comment by deltamualpha** [comment]
Looks like it'll be fixed with the wp-cli 0.24 release, although I'm not sure when that'll be.

**Comment by danielbachhuber** [comment]
Quickstart should use the WP-CLI nightly build instead of the stable.

**Comment by danielbachhuber** [comment]
> Quickstart should use the WP-CLI nightly build instead of the stable.

Oh, I forgot I flagged this a while back: https://github.com/Automattic/vip-quickstart/issues/466

It will require a corresponding update to the Puppet module.

**Comment by mdrovdahl** [comment]
thanks @danielbachhuber I've just now confirmed with a fresh install that the most recent nightly wp-cli build solves this. We'll get Quickstart updated to track that.

vagrant@vip:~$ php /usr/bin/wp --info
PHP binary:	/usr/bin/php5
PHP version:	5.6.22-1+donate.sury.org~precise+1
php.ini used:	/etc/php5/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	/srv/www/wp-cli.yml
WP-CLI project config:	
WP-CLI version:	0.24.0-alpha-4acc61a

**Comment by mdrovdahl** [comment]
oops, will leave open until it's updated
