### ISSUE TITLE
vagrant up hangs "waiting for machine to boot..." 

### ISSUE THREAD

**Issue by mdrovdahl** [Automattic/vip-quickstart#502]
Symptom: vagrant can't connect via ssh even though the virtual-machine is running and listening on port 22 

VAGRANT FAILS TO CONNECT 
markd@xps:~/dev/vip-quickstart$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

VM IS RUNNING AND LISTENING FOR SSH
markd@xps:~/dev/vip-quickstart$ sudo ifconfig | grep -A2 vbox
vboxnet0  Link encap:Ethernet  HWaddr 0a:00:27:00:00:00  
          inet addr:10.86.73.1  Bcast:10.86.73.255  Mask:255.255.255.0
          inet6 addr: fe80::800:27ff:fe00:0/64 Scope:Link
markd@xps:~/dev/vip-quickstart$ telnet 10.86.73.1 22
Trying 10.86.73.1...
Connected to 10.86.73.1.
Escape character is '^]'.
SSH-2.0-OpenSSH_6.7p1 Debian-5+deb8u2
^]

telnet> Connection closed.

**Comment by mdrovdahl** [comment]
Ok...10.86.73.1 was wrong, that's my local sshd.

The VM should be on 10.86.73.80 per https://github.com/Automattic/vip-quickstart/blob/master/Vagrantfile#L17

And, after shutting down my local sshd (to avoid confusion) I can hit the VM sshd at 127.0.0.1:2222

**Comment by mdrovdahl** [comment]
What works:

1. Stopping the failed to boot box via VirtualBox admin gui
2. adding `config.ssh.insert_key = false` to `vip-quickstart/Vagrantfile`
3. vagrant up

It seems the issue may be with the Vagrant client generating/replacing the insecure key:

* http://stackoverflow.com/a/28524909
* https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html

**Comment by mdrovdahl** [comment]
Since a standard Quickstart installation shouldn't be exposed beyond the local host machine...let's make this `config.ssh.insert_key = false` change and see if it helps folks get around this particular machine hanging on boot issue. https://github.com/Automattic/vip-quickstart/pull/503

**Comment by ronrlin** [comment]
I believe this issue is still a problem.  I'm unable to run the VIP Quickstart recipe.  I get the following error on vagrant up:

```
[13] → vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Resuming suspended VM...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by deanwagman** [comment]
Really think this issue needs to be readdressed. Having this issue with the config set to false.

**Comment by ocrunch** [comment]
Been having this issue also for awhile now. setting ```config.ssh.insert_key = false``` doesn't help.

**Comment by ocrunch** [comment]
This happens on fresh installs of quickstarts. I haven't seen anyone address this issue in months.

**Comment by escobar022** [comment]
+. It seems like this is an issue with new set ups of vip-quickstart.

**Comment by jjeaton** [comment]
Ran into this today on a fresh install of vip-quickstart on macOS Sierra. Does anyone have a fix?

**Comment by kasparsd** [comment]
+1 Removing the password and allowing Vagrant to take care of the login fixed the issue for me:

```
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -15,9 +15,6 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.box_url = "http://files.vagrantup.com/precise32.box"
   config.vm.hostname = 'vip.local'
   config.vm.network :private_network, ip: "10.86.73.80"
-  config.ssh.insert_key = false #see https://github.com/Automattic/vip-quickstart/issues/502
-  config.ssh.username = "vagrant"
-  config.ssh.password = "vagrant"
```

**Comment by robertwe** [comment]
Hi,
to make it work I made changes as below:
```
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -15,10 +15,9 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.box_url = "http://files.vagrantup.com/precise32.box"
   config.vm.hostname = 'vip.local'
   config.vm.network :private_network, ip: "10.86.73.80"
-  config.ssh.insert_key = false #see https://github.com/Automattic/vip-quickstart/issues/502
   config.ssh.username = "vagrant"
-  config.ssh.password = "vagrant"
```

After this patch all works as expected. 
My setup:
 - vagrant v1.9.0 (in this version problem with permissions to private key should be fixed),
 - VirtualBox v5.0.30
 - OSX El Capitan

Also here is a list of my vagrant plugins:
```
vagrant-hostsupdater (1.0.2)
vagrant-share (1.1.6, system)
vagrant-triggers (0.5.3)
vagrant-vbguest (0.13.0)
vagrant-vmware-fusion (4.0.15)
```

**Comment by AdnaneX** [comment]
![fghjk](https://cloud.githubusercontent.com/assets/11260121/23042051/05b0cbd0-f48f-11e6-87ce-3afca3b75f65.png)

**Comment by rayrutjes** [comment]
To solve this issue, here is what I did:
- Upgraded VirtualBox to the latest version
- Upgraded Vagrant to the latest version
- Remove the 2 lines as suggested by @robertwe https://github.com/Automattic/vip-quickstart/issues/502#issuecomment-269544488
- `vagrant destroy && vagrant up`
