### ISSUE TITLE
Jetpack apply_filters in latest version breaks QS

### ISSUE THREAD

**Issue by Tarendai** [Automattic/vip-quickstart#510]
The latest Jetpack adds a filter to the `jetpack_is_mobile` function, but we're using it before `apply_filters` is defined, leading to fatal errors.

**Comment by paulschreiber** [comment]
This prevents Jetpack from loading:
```
PHP Fatal error:  Cannot redeclare class Jetpack_User_Agent_Info in /srv/www/wp-content/plugins/jetpack/class.jetpack-user-agent.php on line 116
```

**Comment by Tarendai** [comment]
Moving the `batcache-config.php` loading to `advanced-cache.php` eliminates the need to load that file so early, @paulschreiber can you confirm this resolves the issue at your end too?

**Comment by paulschreiber** [comment]
Seems better now. Thanks!

**Comment by Tarendai** [comment]
Awesome :) Thanks for confirming, reopen this if it becomes an issue again
