### ISSUE TITLE
Creating a new user or site results in fatal error

### ISSUE THREAD

**Issue by jjeaton** [Automattic/vip-quickstart#512]
Due to https://core.trac.wordpress.org/ticket/25239, I am getting a fatal error on a fresh quickstart install when sending an email to the network admin (creating a new user or site).

```Xdebug: Fatal error: Uncaught exception 'phpmailerException' with message 'Invalid address: wordpress@_' in /srv/www/wp/wp-includes/class-phpmailer.php:946 Stack trace: #0 /srv/www/wp/wp-includes/pluggable.php(352): PHPMailer->setFrom('wordpress@_', 'WordPress') #1 /srv/www/wp/wp-includes/ms-functions.php(1244): wp_mail('admin@example.c...', 'New User Regist...', 'New User: test2...') #2 [internal function]: newuser_notify_siteadmin(4) #3 /srv/www/wp/wp-includes/plugin.php(524): call_user_func_array('newuser_notify_...', Array) #4 /srv/www/wp/wp-includes/ms-functions.php(1068): do_action('wpmu_new_user', 4) #5 /srv/www/wp/wp-admin/network/user-new.php(49): wpmu_create_user('test2', 'ba0VQOdGVTY9', 'xxxx234@gma...') #6 {main} thrown in /srv/www/wp/wp-includes/class-phpmailer.php on line 946. Output triggered in /srv/www/wp-content/plugins/query-monitor/collectors/php_errors.php on line 157```

It appears that the from email is set to `wordpress@_` because nginx's `SERVER_NAME` is `_`.

My workaround was to add this into a mu-plugin:

```
add_filter( 'wp_mail_from', function() {
	return 'wordpress@vip.local';
} );
```

Am curious if anyone else has run into this.

**Comment by rd13** [comment]
Can confirm, new site gave us the same fatal error. Added your temp fix to the end of mu_plugin/vip.php.

**Comment by Tarendai** [comment]
The core ticket mentioned has a diff that relies on `$current_blog->domain` to generate the email address, I'm going to test this filter and include it

```
add_filter( 'wp_mail_from', function() {
    global $current_blog; 
    $sitename = $current_blog->domain;
    return 'wordpress@'.$current_blog->domain;
} );
```

It will fail in a non-multisite environment, but that's not relevant to Quickstart
