### ISSUE TITLE
vagrant up fails at SSH command

### ISSUE THREAD

**Issue by sarahmonster** [Automattic/vip-quickstart#514]
Every time I try to `vagrant up`, I end up with this error:

`==> default: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type ini_setting at /tmp/vagrant-puppet/modules-e7d8ecbc74d9b9e0c41d014c884cde0a/php/manifests/config/dwim.pp:28 on node vip`

`The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

I'm able to `vagrant ssh` to log into the machine, and I can see the box powered up in VirtualBox, but I can't see the site in a browser; Firefox can’t establish a connection to the server at `vip.local`.

This was previously working but has suddenly become temperamental. I'm not quite sure how to bugfix, so I'd appreciate any guidance here!

**Comment by joshbetz** [comment]
I think you're missing or need to update submodules. Can you `git submodule update --init --recursive` and try again?

**Comment by sarahmonster** [comment]
Thank you! That seems to have helped matters a bit. Unfortunately, I've now landed on #377/#473, which I've never managed to resolve without rebuilding everything.
