### ISSUE TITLE
Why don't you switch to docker?

### ISSUE THREAD

**Issue by fabn** [Automattic/vip-quickstart#526]
We're using this repository as development environment and also for staging and client preview functionalities and we found the process of bringing up a new instance (or setup a new developer laptop) very long, sometimes frustrating and error prone.

Also from time to time development environment got corrupted in some way and we often have to start from scratch every time that happens (unless we have virtualbox snapshots).

I think that providing a docker image (possibly using docker-compose to build the whole stack) automatically built would be a far superior solution and will provide a better development experience.

In order to get started one should only type `docker-compose up` and magically everything will work. It will also be easier to deploy the same stack on staging servers.

What do you think?

**Comment by joshbetz** [comment]
Working on it :)

**Comment by fabn** [comment]
@joshbetz Awesome. Do you have any timeline or any roadmap we can follow?

**Comment by joshbetz** [comment]
Not at this time.

**Comment by dero** [comment]
Hi @joshbetz, any update on the timeline at this point? The current solution using Vagrant is slow and quite fragile. Any official Docker alternative would result in a much more pleasurable dev experience.

While I don't have too much experience with Docker yet, provided there is some kind of guidance, I'm willing to help the efforts in any way necessary if manpower is what's missing.

**Comment by joshbetz** [comment]
Coming soon. There's no official date yet, but be sure to watch the VIP Blog for updates https://vip.wordpress.com/blog/
