### ISSUE TITLE
Batcache is causing HTTP500's currently

### ISSUE THREAD

**Issue by zamoose** [Automattic/vip-quickstart#527]
https://github.com/Automattic/batcache/pull/73

This is... problematic.

**Comment by skeltoac** [comment]
I thought the point of build_preinitialized_hooks was so 4.7 would work with this kind of code. Is there something wrong with it? Could we get a more complete bug report?

**Comment by joshlevinson** [comment]
@skeltoac Provided fuller detail @ https://github.com/Automattic/batcache/pull/73

**Comment by joshbetz** [comment]
Fixed by https://github.com/Automattic/batcache/pull/76
