### ISSUE TITLE
wpcom_vip_top_posts_array() produces broken links

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/vip-quickstart#528]
wpcom_vip_top_posts_array() produces broken links, such as:

    http://foobar.com?p=0

The problem is in vip-helper-stats-wpcom.php on line 60
```
'post_permalink' 	=> add_query_arg( 'p', $i, home_url() ),
```

The call to `home_url()` should be `home_url( '/' )`.

**Comment by paulschreiber** [comment]
Also filed VIP ticket 57314.

**Comment by sboisvert** [comment]
Done in r261039 on the vip shared plugin. That will be live shortly (5-10 min). running SVN up should solve this.
